environment:
  semver_version: '0.1.0'
version: $(semver_version)-ci{build}
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: $(semver_version)
  assembly_file_version: $(semver_version)
  assembly_informational_version: $(semver_version)
build:
  project: 'Source\Primedice.NET.sln'
before_build:
  - nuget restore
deploy:
  provider: NuGet
  api_key:
    secure: 9Ye4uKc6ajyyP+DceXAUufu0xaGA36Fzz8TM0VLu94+1327wHLQsXbCVS92tPcnp
  on:
    branch: master
    appveyor_repo_tag: true
  artifact: '**\*.nupkg'
